name: Regions without service

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # Install python requirements
      - name: Pip install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Save historical data
        run: |-
          python ./build_regionsService.py
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git pull
          git add -A
          timestamp=$(date -u)
          git commit -m "Update regionsWithoutService $timestamp" || exit 0
          git push